name: Setup and regenerate fixtures

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - labeled

jobs:
  setup-and-regenerate-fixtures:
    if: github.event.label.name == 'regenerate-fixtures'
    runs-on: ubuntu-latest

    steps:
        # No setup step needed, yet.
      - name: Regenerate Fixtures
        uses: codecrafters-io/tester-utils/.github/actions/fixtures@master
        with:
          tester_repo: git-tester
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fixture_generation_token: ${{ secrets.TESTER_FIXTURE_GENERATION_GITHUB_TOKEN }}
